sudo: false
language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run test:coveralls
notifications:
  email: false
deploy:
  provider: heroku
  app: solve-server
  api_key:
    secure: ICSsth6Hq+8KxdxemBbFfPPYpVUIeTpivnwgJxgX7VMI7ef7ImXwVEPO7N05doKA6AGbb30tIpAicXOPE0FT/Mr38WSOUkgEWP3eD6nU5c9q/mYZKB6iRYAfVCx2k93tx5Ouf/0xRJzhdWqPqOv9epqp9jfJX6GcYNfrg9JIv0d4ZDQiNM9XzGivO5U5X4XtIjsDaE6OrlEkoF0ZvavVUNH9aW2aOn95GXXo4QxvPEdZJJrCgtewxRpW8KA5dGFCj/qWuYFcChjhizbUCz67/bpZsLyA8GCPQ4sM3dyIFuP2RTblpsuMTvKUefeN9xpoPaoQY4iI5nlN1YyYBJ/D9oU98KhGVZQK51DWFHQ0eu/bjjQ+RHimegqxGmRAP9IvO+xGk0roRKr9qHm3AHTeAX3O/Zq/p0Xw4srTWAYMtgovGT+E3emlZrUX5D1EoASPHthzOCCmreBVzv3WuwUIA8CdcEKJXydy5nvpl+Y2KGEjWyhmu8Mv+WfjQj0P1961LLippTxDxs+pppmi1ZFDieXGyRn+IR0KqLYfMke84TYVyeMz56GIcmQlk97JmUv2OtgXg+msh2dbyU2jdQUxwh8pZIGr4ZzLcmq6Q3DP9cE0rAZ6Uij3gruwYO/t25aXiAaj8O9ib0fCd1DprJmkFxBO8ckSRSbJmZ519RTTlMc=
